### ISSUE TITLE
Overlapping menu when selecting a category on Edit Item screen.

### ISSUE THREAD

**Issue by gin93r** [kmgalanakis/Inceptive-Multiple-Extra-Field-Groups-for-K2#4]
When adding a new item, selecting a category breaks the layout. There is a div that gets added to the DOM with the id "mefgTabs". If I delete that DOM element in dev tools, then the layout gets fixed. Using version 2.10.3 of K2 and version 1.3 of imefg.

Before selecting a category:
![new_item_before_selecting_category](https://user-images.githubusercontent.com/5880428/83021868-a5c3cd80-9ff8-11ea-9b3d-9c5ed7c34ab4.png)

After selecting a category:
![new_item_after_selecting_category](https://user-images.githubusercontent.com/5880428/83021867-a52b3700-9ff8-11ea-9cda-753dadc79f6c.png)

**Comment by TThrane** [comment]
Try this:

In backend -> templates -> admin templates -> isis -> edit template -> css -> custom.css ->
#k2AdminContainer.K2AdminViewItem.isEditForm > #mefgTabs {
      display: none;
}

**Comment by gin93r** [comment]
@TThrane ~~Thanks for the response. I'm don't seem to be able to see the files in the admin section itself. However, I've added a custom.css file with the rules above in /administrator/templates/isis/css/ and the issue still persists.~~

Nevermind, I figured it out. Thanks.

**Comment by TThrane** [comment]
Yes, you have to make the custom.css yourself, if it's not there.
Did it work?

**Comment by gin93r** [comment]
I did make it but it wasn't applying the rules from it. I ended up adding the rule to the template.css file and that worked after clearing the cache. It's a custom theme that I inherited so maybe there's something preventing it from being loaded.

There wasn't a file list at all in admin ui for the template.

Either way, it's working now.
